export interface Quote {
  text: string;
  author: string;
  domain: string;
}

export const ALL_QUOTES: Quote[] = [
  // BUSINESS
  { text: "Chase the vision, not the money; the money will end up following you.", author: "Tony Hsieh", domain: "BUSINESS" },
  { text: "Your most unhappy customers are your greatest source of learning.", author: "Bill Gates", domain: "BUSINESS" },
  { text: "The best way to predict the future is to create it.", author: "Peter Drucker", domain: "BUSINESS" },
  { text: "It's not about ideas. It's about making ideas happen.", author: "Scott Belsky", domain: "BUSINESS" },
  { text: "Success is not in what you have, but who you are.", author: "Bo Bennett", domain: "BUSINESS" },
  { text: "The secret of business is to know something that nobody else knows.", author: "Aristotle Onassis", domain: "BUSINESS" },
  { text: "Don't find customers for your products, find products for your customers.", author: "Seth Godin", domain: "BUSINESS" },
  { text: "A brand is no longer what we tell the consumer it is - it is what consumers tell each other it is.", author: "Scott Cook", domain: "BUSINESS" },
  { text: "Make every detail perfect and limit the number of details to perfect.", author: "Jack Dorsey", domain: "BUSINESS" },
  { text: "The entrepreneur always searches for change, responds to it, and exploits it as an opportunity.", author: "Peter Drucker", domain: "BUSINESS" },
  { text: "Risk more than others think is safe. Dream more than others think is practical.", author: "Howard Schultz", domain: "BUSINESS" },
  { text: "The critical ingredient is getting off your butt and doing something.", author: "Nolan Bushnell", domain: "BUSINESS" },
  { text: "Good companies will meet needs. Great companies will create markets.", author: "Philip Kotler", domain: "BUSINESS" },
  { text: "If you really look closely, most overnight successes took a long time.", author: "Steve Jobs", domain: "BUSINESS" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", domain: "BUSINESS" },
  { text: "Opportunities don't happen. You create them.", author: "Chris Grosser", domain: "BUSINESS" },
  { text: "If you can't explain it simply, you don't understand it well enough.", author: "Albert Einstein", domain: "BUSINESS" },
  { text: "Without a customer, you don't have a business - you have a hobby.", author: "Don Peppers", domain: "BUSINESS" },

  // TECH
  { text: "Any sufficiently advanced technology is indistinguishable from magic.", author: "Arthur C. Clarke", domain: "TECH" },
  { text: "The best way to predict the future is to invent it.", author: "Alan Kay", domain: "TECH" },
  { text: "Software is eating the world.", author: "Marc Andreessen", domain: "TECH" },
  { text: "Talk is cheap. Show me the code.", author: "Linus Torvalds", domain: "TECH" },
  { text: "First, solve the problem. Then, write the code.", author: "John Johnson", domain: "TECH" },
  { text: "Code is like humor. When you have to explain it, it's bad.", author: "Cory House", domain: "TECH" },
  { text: "Simplicity is the soul of efficiency.", author: "Austin Freeman", domain: "TECH" },
  { text: "Make it work, make it right, make it fast.", author: "Kent Beck", domain: "TECH" },
  { text: "The function of good software is to make the complex appear simple.", author: "Grady Booch", domain: "TECH" },
  { text: "Programs must be written for people to read, and only incidentally for machines to execute.", author: "Harold Abelson", domain: "TECH" },
  { text: "The most disruptive thing about technology is not the technology itself - it's the behavior it enables.", author: "Unknown", domain: "TECH" },
  { text: "Technology is best when it brings people together.", author: "Matt Mullenweg", domain: "TECH" },
  { text: "Move fast and break things. Unless you are breaking stuff, you are not moving fast enough.", author: "Mark Zuckerberg", domain: "TECH" },
  { text: "In software, the hard part isn't solving problems - it's deciding what problems to solve.", author: "Paul Graham", domain: "TECH" },
  { text: "You don't have to be a genius to build great software. You have to be stubborn.", author: "DHH", domain: "TECH" },
  { text: "The best error message is the one that never shows up.", author: "Thomas Fuchs", domain: "TECH" },
  { text: "Every great developer you know got there by solving problems they were unqualified to solve.", author: "Patrick McKenzie", domain: "TECH" },

  // CAREER
  { text: "Choose a job you love and you will never have to work a day in your life.", author: "Confucius", domain: "CAREER" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", domain: "CAREER" },
  { text: "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do great work.", author: "Steve Jobs", domain: "CAREER" },
  { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill", domain: "CAREER" },
  { text: "Opportunities are usually disguised as hard work, so most people don't recognize them.", author: "Ann Landers", domain: "CAREER" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson", domain: "CAREER" },
  { text: "I never dreamed about success. I worked for it.", author: "Estée Lauder", domain: "CAREER" },
  { text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson", domain: "CAREER" },
  { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis", domain: "CAREER" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe", domain: "CAREER" },
  { text: "You don't get what you wish for. You get what you work for.", author: "Daniel Habit", domain: "CAREER" },
  { text: "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.", author: "Dale Carnegie", domain: "CAREER" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain", domain: "CAREER" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", domain: "CAREER" },
  { text: "A career is built one decision at a time - make each one count.", author: "Unknown", domain: "CAREER" },
  { text: "The people who get on in this world are the people who get up and look for the circumstances they want.", author: "George Bernard Shaw", domain: "CAREER" },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau", domain: "CAREER" },

  // LIFE
  { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein", domain: "LIFE" },
  { text: "Life is what happens when you're busy making other plans.", author: "John Lennon", domain: "LIFE" },
  { text: "The purpose of our lives is to be happy.", author: "Dalai Lama", domain: "LIFE" },
  { text: "You only live once, but if you do it right, once is enough.", author: "Mae West", domain: "LIFE" },
  { text: "In the end, it's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln", domain: "LIFE" },
  { text: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", author: "Mother Teresa", domain: "LIFE" },
  { text: "When you reach the end of your rope, tie a knot in it and hang on.", author: "Franklin D. Roosevelt", domain: "LIFE" },
  { text: "Always remember that you are absolutely unique. Just like everyone else.", author: "Margaret Mead", domain: "LIFE" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson", domain: "LIFE" },
  { text: "You will face many defeats in life, but never let yourself be defeated.", author: "Maya Angelou", domain: "LIFE" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela", domain: "LIFE" },
  { text: "In the long run, the sharpest weapon of all is a kind and gentle spirit.", author: "Anne Frank", domain: "LIFE" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle", domain: "LIFE" },
  { text: "Whoever is happy will make others happy too.", author: "Anne Frank", domain: "LIFE" },
  { text: "Do not let making a living prevent you from making a life.", author: "John Wooden", domain: "LIFE" },
  { text: "Life shrinks or expands in proportion to one's courage.", author: "Anaïs Nin", domain: "LIFE" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins", domain: "LIFE" },

  // ACADEMIC
  { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela", domain: "ACADEMIC" },
  { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi", domain: "ACADEMIC" },
  { text: "The more that you read, the more things you will know.", author: "Dr. Seuss", domain: "ACADEMIC" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin", domain: "ACADEMIC" },
  { text: "The beautiful thing about learning is that no one can take it away from you.", author: "B.B. King", domain: "ACADEMIC" },
  { text: "Intelligence plus character - that is the goal of true education.", author: "Martin Luther King Jr.", domain: "ACADEMIC" },
  { text: "Education is not preparation for life; education is life itself.", author: "John Dewey", domain: "ACADEMIC" },
  { text: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle", domain: "ACADEMIC" },
  { text: "It is not that I'm so smart. But I stay with the questions much longer.", author: "Albert Einstein", domain: "ACADEMIC" },
  { text: "Curiosity is the engine of achievement.", author: "Ken Robinson", domain: "ACADEMIC" },
  { text: "The mind is not a vessel to be filled, but a fire to be kindled.", author: "Plutarch", domain: "ACADEMIC" },
  { text: "Research is what I'm doing when I don't know what I'm doing.", author: "Wernher von Braun", domain: "ACADEMIC" },
  { text: "Science is a way of thinking much more than it is a body of knowledge.", author: "Carl Sagan", domain: "ACADEMIC" },
  { text: "The more I learn, the more I realize how much I don't know.", author: "Albert Einstein", domain: "ACADEMIC" },
  { text: "A person who won't read has no advantage over one who can't read.", author: "Mark Twain", domain: "ACADEMIC" },
  { text: "Study hard what interests you the most in the most undisciplined, irreverent and original manner possible.", author: "Richard Feynman", domain: "ACADEMIC" },

  // DECISION
  { text: "In any moment of decision, the best thing you can do is the right thing.", author: "Theodore Roosevelt", domain: "DECISION" },
  { text: "It is in your moments of decision that your destiny is shaped.", author: "Tony Robbins", domain: "DECISION" },
  { text: "Once you make a decision, the universe conspires to make it happen.", author: "Ralph Waldo Emerson", domain: "DECISION" },
  { text: "The risk of a wrong decision is preferable to the terror of indecision.", author: "Maimonides", domain: "DECISION" },
  { text: "Not making a decision is itself a decision.", author: "Unknown", domain: "DECISION" },
  { text: "Decide what you want, decide what you are willing to exchange for it.", author: "H.L. Hunt", domain: "DECISION" },
  { text: "When faced with two equally tough choices, most people choose the third choice - to not choose.", author: "Jarod Kintz", domain: "DECISION" },
  { text: "A good decision is based on knowledge and not on numbers.", author: "Plato", domain: "DECISION" },
  { text: "The quality of your life is determined by the quality of your decisions.", author: "Unknown", domain: "DECISION" },
  { text: "You cannot make progress without making decisions.", author: "Jim Rohn", domain: "DECISION" },
  { text: "In life, you will make tough choices. The measure of who you are is how you handle them.", author: "Unknown", domain: "DECISION" },
  { text: "Decision is the spark that ignites action.", author: "Wilferd Peterson", domain: "DECISION" },
  { text: "A wrong decision isn't forever; it can always be amended. But indecision is final.", author: "Felicity Huffman", domain: "DECISION" },
  { text: "Clarity about what matters provides clarity about what does not.", author: "Cal Newport", domain: "DECISION" },
  { text: "The choices we make, not the chances we take, determine our destiny.", author: "Unknown", domain: "DECISION" },
  { text: "Reversible decisions deserve five minutes. Irreversible decisions deserve five days.", author: "Unknown", domain: "DECISION" }
];
